// ============================================================================
// MarketFlow: unsubscribe — Supabase Edge Function (public, no auth)
// ============================================================================
// GET  — a person clicked the unsubscribe link in an email client / browser.
//        Returns a small HTML confirmation page.
// POST — RFC 8058 "List-Unsubscribe-Post: One-Click". Mail providers
//        (Gmail, Yahoo, etc.) call this automatically when the person clicks
//        "Unsubscribe" in their inbox UI, with NO page load. Must respond
//        quickly with a bare 200 and do the unsubscribe silently.
//
// Query params (both GET and POST): ?c=<contactId>&w=<workspaceId>&t=<token>
//
// Security: token = HMAC-SHA256(UNSUBSCRIBE_SECRET, `${contactId}:${workspaceId}`),
// truncated to 32 hex chars, generated by send-campaign at send time and
// embedded in the email. Without a valid token, a contactId alone (even if
// guessed) cannot be used to unsubscribe someone else's contact.
//
// Requires: UNSUBSCRIBE_SECRET, SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY
// Deploy with verify_jwt = false — this is a public link with no session.
// ============================================================================

import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";

const UNSUBSCRIBE_SECRET = Deno.env.get("UNSUBSCRIBE_SECRET");
const SUPABASE_URL = Deno.env.get("SUPABASE_URL")!;
const SUPABASE_SERVICE_ROLE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;

async function computeToken(contactId: string, workspaceId: string): Promise<string> {
  const key = await crypto.subtle.importKey(
    "raw",
    new TextEncoder().encode(UNSUBSCRIBE_SECRET),
    { name: "HMAC", hash: "SHA-256" },
    false,
    ["sign"],
  );
  const sig = await crypto.subtle.sign("HMAC", key, new TextEncoder().encode(`${contactId}:${workspaceId}`));
  return Array.from(new Uint8Array(sig)).map((b) => b.toString(16).padStart(2, "0")).join("").slice(0, 32);
}

function htmlResponse(body: string, status = 200) {
  return new Response(
    `<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Unsubscribe</title>
    <style>body{font-family:system-ui,sans-serif;max-width:480px;margin:80px auto;text-align:center;color:#1a1a1a;padding:0 20px}h1{font-size:20px}p{color:#666;line-height:1.5}</style>
    </head><body>${body}</body></html>`,
    { status, headers: { "Content-Type": "text/html; charset=utf-8" } },
  );
}

function plainResponse(status = 200) {
  return new Response(null, { status });
}

Deno.serve(async (req: Request) => {
  const url = new URL(req.url);
  const contactId = url.searchParams.get("c");
  const workspaceId = url.searchParams.get("w");
  const token = url.searchParams.get("t");
  const isOneClick = req.method === "POST";

  if (!UNSUBSCRIBE_SECRET) {
    return isOneClick
      ? plainResponse(500)
      : htmlResponse("<h1>Unsubscribe unavailable</h1><p>This link is temporarily misconfigured. Please contact the sender directly.</p>", 500);
  }

  if (!contactId || !workspaceId || !token) {
    return isOneClick
      ? plainResponse(400)
      : htmlResponse("<h1>Invalid unsubscribe link</h1><p>This link is missing required information.</p>", 400);
  }

  const expected = await computeToken(contactId, workspaceId);
  if (token !== expected) {
    return isOneClick
      ? plainResponse(403)
      : htmlResponse("<h1>Invalid or expired link</h1><p>We couldn't verify this unsubscribe request.</p>", 403);
  }

  const admin = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY);

  const { error: updateErr } = await admin
    .from("contacts")
    .update({ status: "Unsubscribed" })
    .eq("id", contactId)
    .eq("workspace_id", workspaceId);

  if (updateErr) {
    console.error("Unsubscribe update failed:", updateErr);
    return isOneClick
      ? plainResponse(500)
      : htmlResponse("<h1>Something went wrong</h1><p>Please try again later.</p>", 500);
  }

  await admin.from("email_events").insert({
    contact_id: contactId,
    workspace_id: workspaceId,
    event_type: "unsubscribed",
    metadata: { via: isOneClick ? "one-click-header" : "link-click" },
  });

  if (isOneClick) {
    return plainResponse(200);
  }

  return htmlResponse(
    "<h1>You're unsubscribed</h1><p>You won't receive any more marketing emails from this sender. If this was a mistake, contact the sender directly to resubscribe.</p>",
  );
});
