import { useQueries } from "@tanstack/react-query";
import { Link } from "wouter";
import { Users, Mail, MousePointerClick, TrendingUp, UserPlus, FilePlus, Workflow, Tags as TagsIcon, ArrowRight, Activity } from "lucide-react";
import { ResponsiveContainer, AreaChart, Area, XAxis, YAxis, CartesianGrid, Tooltip } from "recharts";
import { KpiCard, LoadingState } from "@/components/shared";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { formatNumber, formatPercent, timeAgo } from "@/lib/format";
import { useWorkspace } from "@/hooks/use-workspace";

const eventTypeColors: Record<string, string> = { email_sent:"bg-blue-100 text-blue-700 dark:bg-blue-950 dark:text-blue-400", email_delivered:"bg-green-100 text-green-700 dark:bg-green-950 dark:text-green-400", email_opened:"bg-purple-100 text-purple-700 dark:bg-purple-950 dark:text-purple-400", email_clicked:"bg-teal-100 text-teal-700 dark:bg-teal-950 dark:text-teal-400", email_bounced:"bg-orange-100 text-orange-700 dark:bg-orange-950 dark:text-orange-400", email_unsubscribed:"bg-red-100 text-red-700 dark:bg-red-950 dark:text-red-400" };
const quickActions = [{label:"Add Contact",icon:UserPlus,href:"/contacts",color:"bg-blue-500"},{label:"Create Campaign",icon:FilePlus,href:"/campaigns",color:"bg-green-500"},{label:"Create Automation",icon:Workflow,href:"/automations",color:"bg-purple-500"},{label:"Create Segment",icon:TagsIcon,href:"/segments",color:"bg-orange-500"}];
function metadata(value: unknown) { if (!value) return {}; if (typeof value === "object") return value as Record<string,any>; try { return JSON.parse(String(value)); } catch { return {}; } }

export default function Dashboard() {
  const { currentWorkspace, loading: workspaceLoading } = useWorkspace();
  const [contactsQ,campaignsQ,automationsQ,eventsQ] = useQueries({queries:[
    {queryKey:["/api/contacts"],enabled:Boolean(currentWorkspace)},
    {queryKey:["/api/campaigns"],enabled:Boolean(currentWorkspace)},
    {queryKey:["/api/automations"],enabled:Boolean(currentWorkspace)},
    {queryKey:["/api/email-events"],enabled:Boolean(currentWorkspace)},
  ]});
  if (workspaceLoading || [contactsQ,campaignsQ,automationsQ,eventsQ].some(q=>q.isLoading)) return <LoadingState label="Loading dashboard..."/>;
  if (!currentWorkspace) return <LoadingState label="Select a workspace to view the dashboard."/>;
  const contacts=(contactsQ.data??[]) as any[], campaigns=(campaignsQ.data??[]) as any[], automations=(automationsQ.data??[]) as any[], events=(eventsQ.data??[]) as any[];
  const sent=events.filter(e=>e.eventType==="email_sent"), opened=events.filter(e=>e.eventType==="email_opened"), clicked=events.filter(e=>e.eventType==="email_clicked");
  const openRate=sent.length?opened.length/sent.length*100:0, clickRate=sent.length?clicked.length/sent.length*100:0;
  const engaged=new Set([...opened,...clicked].map(e=>e.contactId).filter(Boolean)).size, activeAutomations=automations.filter(a=>a.status==="active").length;
  const months=Array.from({length:12},(_,i)=>{const d=new Date();d.setMonth(d.getMonth()-(11-i),1);return{date:d,month:d.toLocaleString(undefined,{month:"short"}),contacts:0,opens:0};});
  contacts.forEach(c=>{const d=new Date(c.createdAt),m=months.find(x=>x.date.getFullYear()===d.getFullYear()&&x.date.getMonth()===d.getMonth());if(m)m.contacts++;});
  opened.forEach(e=>{const d=new Date(e.occurredAt),m=months.find(x=>x.date.getFullYear()===d.getFullYear()&&x.date.getMonth()===d.getMonth());if(m)m.opens++;});
  const performance=campaigns.map(c=>{const ce=events.filter(e=>e.campaignId===c.id),s=ce.filter(e=>e.eventType==="email_sent").length,o=ce.filter(e=>e.eventType==="email_opened").length,k=ce.filter(e=>e.eventType==="email_clicked").length;return{id:c.id,name:c.name,sent:s,openRate:s?o/s*100:0,clickRate:s?k/s*100:0};});
  const recent=[...events].sort((a,b)=>new Date(b.occurredAt||b.createdAt).getTime()-new Date(a.occurredAt||a.createdAt).getTime()).slice(0,8);
  return <div className="space-y-6">
    <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-4"><KpiCard label="Total Contacts" value={formatNumber(contacts.length)} icon={Users} color="blue"/><KpiCard label="Emails Sent" value={formatNumber(sent.length)} icon={Mail} color="purple"/><KpiCard label="Open Rate" value={formatPercent(openRate)} icon={TrendingUp} color="green"/><KpiCard label="Click Rate" value={formatPercent(clickRate)} icon={MousePointerClick} color="orange"/></div>
    <div className="grid grid-cols-1 gap-4 lg:grid-cols-3"><Card className="lg:col-span-2"><CardContent className="p-5"><div className="mb-4 flex items-center justify-between"><div><h3 className="text-sm font-semibold">Contact Growth & Email Engagement</h3><p className="text-xs text-muted-foreground mt-0.5">Last 12 months</p></div><Badge variant="secondary" className="text-xs">Live</Badge></div><ResponsiveContainer width="100%" height={280}><AreaChart data={months}><defs><linearGradient id="colorContacts" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="hsl(var(--chart-1))" stopOpacity={.3}/><stop offset="95%" stopColor="hsl(var(--chart-1))" stopOpacity={0}/></linearGradient><linearGradient id="colorOpens" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="hsl(var(--chart-2))" stopOpacity={.3}/><stop offset="95%" stopColor="hsl(var(--chart-2))" stopOpacity={0}/></linearGradient></defs><CartesianGrid strokeDasharray="3 3" stroke="hsl(var(--border))"/><XAxis dataKey="month" tick={{fontSize:12}}/><YAxis tick={{fontSize:12}}/><Tooltip/><Area type="monotone" dataKey="contacts" name="New Contacts" stroke="hsl(var(--chart-1))" fill="url(#colorContacts)" strokeWidth={2}/><Area type="monotone" dataKey="opens" name="Opens" stroke="hsl(var(--chart-2))" fill="url(#colorOpens)" strokeWidth={2}/></AreaChart></ResponsiveContainer></CardContent></Card>
    <Card><CardContent className="p-5"><h3 className="text-sm font-semibold mb-4">Quick Actions</h3><div className="grid grid-cols-2 gap-3">{quickActions.map(a=>{const I=a.icon;return <Link key={a.label} href={a.href}><div className="flex flex-col items-center gap-2 rounded-lg border border-border p-4 hover:border-primary hover:bg-muted/50 cursor-pointer"><div className={`flex h-10 w-10 items-center justify-center rounded-lg ${a.color} text-white`}><I className="h-5 w-5"/></div><span className="text-xs font-medium text-center">{a.label}</span></div></Link>;})}</div><div className="mt-5 border-t border-border pt-4 grid grid-cols-2 gap-3 text-center"><div><div className="text-xl font-bold text-green-600">{engaged.toLocaleString()}</div><div className="text-xs text-muted-foreground">Engaged Contacts</div></div><div><div className="text-xl font-bold text-purple-600">{activeAutomations}</div><div className="text-xs text-muted-foreground">Active Automations</div></div></div></CardContent></Card></div>
    <div className="grid grid-cols-1 gap-4 lg:grid-cols-3"><Card className="lg:col-span-2"><CardContent className="p-5"><div className="mb-4 flex items-center justify-between"><h3 className="text-sm font-semibold">Campaign Performance</h3><Link href="/analytics"><Button variant="ghost" size="sm">View All <ArrowRight className="ml-1 h-3 w-3"/></Button></Link></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b"><th className="pb-2 text-left">Campaign</th><th className="pb-2 text-right">Sent</th><th className="pb-2 text-right">Open Rate</th><th className="pb-2 text-right">Click Rate</th></tr></thead><tbody>{performance.slice(0,5).map(c=><tr key={c.id} className="border-b border-border/50"><td className="py-2.5 font-medium">{c.name}</td><td className="py-2.5 text-right">{formatNumber(c.sent)}</td><td className="py-2.5 text-right">{formatPercent(c.openRate)}</td><td className="py-2.5 text-right">{formatPercent(c.clickRate)}</td></tr>)}</tbody></table>{!performance.length&&<p className="py-8 text-center text-sm text-muted-foreground">No campaigns yet.</p>}</div></CardContent></Card><Card><CardContent className="p-5"><h3 className="text-sm font-semibold mb-4">Workspace Overview</h3><div className="space-y-4"><div><div className="text-2xl font-bold">{contacts.length.toLocaleString()}</div><div className="text-xs text-muted-foreground">Contacts in this workspace</div></div><div><div className="text-2xl font-bold">{campaigns.length}</div><div className="text-xs text-muted-foreground">Campaigns</div></div><div><div className="text-2xl font-bold">{automations.length}</div><div className="text-xs text-muted-foreground">Automations</div></div></div></CardContent></Card></div>
    <Card><CardContent className="p-5"><div className="mb-4 flex items-center gap-2"><Activity className="h-4 w-4 text-muted-foreground"/><h3 className="text-sm font-semibold">Recent Activity</h3><Badge variant="secondary" className="text-xs ml-auto">Live</Badge></div><div className="space-y-2">{recent.map(e=>{const m=metadata(e.metadata),t=e.occurredAt||e.createdAt;return <div key={e.id} className="flex items-center gap-3 py-2 border-b border-border/50 last:border-0"><span className={`inline-flex items-center rounded-full px-2 py-0.5 text-xs font-medium ${eventTypeColors[e.eventType]||"bg-muted"}`}>{String(e.eventType||"event").replace(/_/g," ")}</span><span className="text-sm text-muted-foreground flex-1 truncate">{m.campaignName||"Campaign"}{e.contactId?` · Contact #${e.contactId}`:""}</span><span className="text-xs text-muted-foreground">{t?timeAgo(t):"—"}</span></div>})}{!recent.length&&<p className="py-6 text-center text-sm text-muted-foreground">No activity yet.</p>}</div></CardContent></Card>
  </div>;
}
